# Лабораторная работа 1
# "Построение матрицы расстояний между случайными точками"

## Списки в Python

### Создание списков

Для работы со спиками в Python не требуется особой библиотеки, что, конечно, радует. 
Для создание списки достаточно просто задать переменную для его хранения и присвоить ей содержимое списка, которое указывается в [].

#### Списки могут содержать как целые числа

In [ ]:
listInt = [1,2,3,4,5]
print (listInt)

[1, 2, 3, 4, 5]


#### так и вещественные

In [ ]:
listFloat = [1.5,2.4,3.8,4.1,5.9]
print (listFloat)

[1.5, 2.4, 3.8, 4.1, 5.9]


#### да и вообще любой тип данных

In [ ]:
# список слов
listWords = ['Python','List']
print (listWords)

['Python', 'List']


In [ ]:
# список булевых значений
listBool = [False, True, False]
print (listBool)

[False, True, False]


Также можно создать просто пустой список

In [ ]:
listEmpty = []
print (listEmpty)

[]


### Операции со списками

Для добавление элемента в конец списка используется метод append()

In [ ]:
listEmpty.append(2)
print (listEmpty)

[2]


Когда нужно добавить много элементов в окнец списка используется метод extend(), хотя им можно добавлять и по 1 элементу

In [ ]:
listEmpty.extend(listInt)
print (listEmpty)

[2, 1, 2, 3, 4, 5]


Очистить список можно методом clear()

In [ ]:
listEmpty.clear()
print (listEmpty)

[]


Больше информации по работе со спиками есть здесь https://www.ibm.com/developerworks/ru/library/l-python_part_3/

Списки универсальный инструмент в Python и их можно заполнять не только вручную, но и с помощью циклов.
Сделаем список целых чисел от 0 до 9. Диапазон чисел задается методом range()

In [ ]:
listRange= [i for i in range(10)]
print (listRange)

А сейчас сделаем список четных чисел от 0 до 9

In [ ]:
listOdd = [i for i in range(10) if i%2 == 0]
print (listOdd)

[0, 2, 4, 6, 8]


##### Обращение к элементам списка

Чтобы обратиться к элементу списка нужно указаить имя списка и в [] номер элемента.
Обратимся к 0 элементу списка listOdd

In [ ]:
print (listOdd[0])

А теперь к последнему

In [ ]:
print (listOdd[-1])

Также можно обращаться к "кускам" списка

In [ ]:
print (listOdd[1:5])

## Массивы в Python

Работа с массивами в Python организована в библиотеке Numpy. Для начала ее нужно импортировать в проект. Сделаем это и сохраним библиотеку под коротким именем np

In [ ]:
import numpy as np

### Создание векторов

Самый простой способ создать вектор в `NumPy` — задать его явно с помощью __`numpy.array(list, dtype=None, ...)`__.

Параметр __`list`__ задает итерируемый объект, из которого можно создать вектор. Например, в качестве этого параметра можно задать список чисел. Параметр __`dtype`__ задает тип значений вектора, например, __`float`__ — для вещественных значений и __`int`__ — для целочисленных. Если этот параметр не задан, то тип данных будет определен из типа элементов первого аргумента. 

In [ ]:
vectorInt = np.array([1, 2, 3, 4])
print ('Вектор:\n', vectorInt)

NameError: ignored

In [ ]:
# или из готового списка
vectorIntList = np.array(listInt)
print (vectorIntList)

NameError: ignored

Другим способом задания вектора является функция numpy.arange(([start, ]stop, [step, ]...), которая задает последовательность чисел заданного типа из промежутка [start, stop) через шаг step:

In [ ]:
vectorFloat = np.arange(start=0, stop=1, step=0.3, dtype=float)
print ('Вещественный вектор чисел от 0 до 1 с шагом 0.3:\n', vectorFloat)

Можно создавать и вектора случайных чисел через метод np.random.sample(), где в качестве аргументов указывается количество случайных чисел

In [ ]:
vectorRand = np.random.sample(10)
print (vectorRand)

Подробнее про работу со случайными числами в Python и генераторы случайных чисел есть в http://librerussia.blogspot.com/2015/02/python-random.html

## Задание 1

На первом шаге создадим координаты X,Y случайных точек
Создайте 2 списка векторов случайных чисел X и Y. В каждом из них должны быть 3 вектора случайных чисел с 5, 10 и 30 случайными числами

In [4]:
import numpy as np
import random

X = np.array([np.random.sample(5), np.random.sample(10), np.random.sample(30)])
Y = np.array([np.random.sample(5), np.random.sample(10), np.random.sample(30)])
print(X, Y)

[array([0.02656333, 0.76601895, 0.58703525, 0.61670984, 0.39952935])
 array([0.22146757, 0.80521837, 0.35728464, 0.55786232, 0.57200253,
       0.96656349, 0.27904817, 0.34970525, 0.54172029, 0.14463845])
 array([0.55526149, 0.31304782, 0.32711999, 0.48470899, 0.5462354 ,
       0.26989769, 0.49689866, 0.51987215, 0.44184286, 0.27201092,
       0.76391272, 0.94413586, 0.66132398, 0.2334857 , 0.89217465,
       0.61506372, 0.05508489, 0.17467043, 0.98732445, 0.87805361,
       0.90009333, 0.52258323, 0.31247843, 0.16581948, 0.39350217,
       0.89994604, 0.02855207, 0.93443982, 0.58203239, 0.73803685])] [array([0.03785873, 0.46607471, 0.23604111, 0.77497209, 0.76007057])
 array([0.33565696, 0.43363318, 0.96800355, 0.84971223, 0.84314511,
       0.85399923, 0.22615278, 0.64416264, 0.4375247 , 0.11539657])
 array([0.09674551, 0.51331826, 0.28364152, 0.85124787, 0.00574755,
       0.63399394, 0.22136861, 0.42530518, 0.31810343, 0.89606312,
       0.38864066, 0.55947   , 0.96267869, 0.57811

### Операции над векторами

Векторы в NumPy можно складывать, вычитать, умножать на число и умножать на другой вектор (покоординатно):

In [ ]:
a = np.array([1, 2, 3])
b = np.array([6, 5, 4])
k = 2

print ('Вектор a:', a)
print ('Вектор b:', b)
print ('Число k:', k)

Вектор a: [1 2 3]
Вектор b: [6 5 4]
Число k: 2


In [ ]:
print ('Сумма a и b:\n', a + b)
print ('Разность a и b:\n', a + b)
print ('Покоординатное умножение a и b:\n', a * b)
print ('Умножение вектора на число (осуществляется покоординатно):\n', k * a)

Сумма a и b:
 [7 7 7]
Разность a и b:
 [7 7 7]
Покоординатное умножение a и b:
 [ 6 10 12]
Умножение вектора на число (осуществляется покоординатно):
 [2 4 6]


### Нормы векторов

Вспомним некоторые нормы, которые можно ввести в пространстве  ℝn , и рассмотрим, с помощью каких библиотек и функций их можно вычислять в NumPy.

#### p-норма

p-норма (норма Гёльдера) для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
\left\Vert x \right\Vert_{p} = \left( \sum_{i=1}^n \left| x_{i} \right|^{p} \right)^{1 / p},~p \geq 1.
$$

В частных случаях при:
* $p = 1$ получаем $\ell_{1}$ норму
* $p = 2$ получаем $\ell_{2}$ норму

Далее нам понабится модуль `numpy.linalg`, реализующий некоторые приложения линейной алгебры. Для вычисления различных норм мы используем функцию __`numpy.linalg.norm(x, ord=None, ...)`__, где __`x`__ — исходный вектор, __`ord`__ — параметр, определяющий норму (мы рассмотрим два варианта его значений — 1 и 2). Импортируем эту функцию:

In [ ]:
from numpy.linalg import norm

### $\ell_{1}$ норма

$\ell_{1}$ норма 
(также известная как [манхэттенское расстояние](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%81%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B8%D1%85_%D0%BA%D0%B2%D0%B0%D1%80%D1%82%D0%B0%D0%BB%D0%BE%D0%B2))
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

Ей в функции __`numpy.linalg.norm(x, ord=None, ...)`__ соответствует параметр __`ord=1`__.

In [ ]:
a = np.array([1, 2, -3])
print ('L1 норма вектора a:\n', norm(a, ord=1))

L1 норма вектора a:
 6.0


### $\ell_{2}$ норма

$\ell_{2}$ норма (также известная как евклидова норма)
для вектора $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ вычисляется по формуле:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

Ей в функции __`numpy.linalg.norm(x, ord=None, ...)`__ соответствует параметр __`ord=2`__.

In [ ]:
print ('L2 норма вектора a:\n', norm(a, ord=2))

L2 норма вектора a:
 3.7416573867739413


### Расстояние между векторами

Для двух векторов $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ и $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$ $\ell_{1}$ и $\ell_{2}$ раccтояния вычисляются по следующим формулам соответственно:

$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} = 
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$

In [ ]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])
print ('L1 расстояние между векторами a и b:\n', norm(a - b, ord=1))

L1 расстояние между векторами a и b:
 17.0


In [ ]:
print ('L2 расстояние между векторами a и b:\n', norm(a - b, ord=2))

L2 расстояние между векторами a и b:
 12.12435565298214


## Задание 2

Напишите функцию для расчета расстояния (как Евклидового, так и Манхэттенновского) между двумя точками, координаты которых, находятся в векторе Х и Y. Причем вектора содержат координаты не одной, а множества точек. Функция принимает на вход вектора с координатами Х и Y, а также переменную mode, указывающую режим расчета - Евклидово или Манхэттоновское расстояние. 
Функция возвращает список расстояний между точками.
Для расчета расстояния использовать метод norm

In [10]:
import numpy as np
from numpy.linalg import norm

def dist(X,Y,mode):
    Dist = [] # лист дистанций
    for i in range(len(X)): #бежим по всему листу x
      for j in range(len(Y)): #по всему y
        point1 = np.array([X[i],Y[i]]) #преобразоываем в массив
        point2 = np.array([X[j],Y[j]]) #в массив
        Dist.append(norm(point1-point2, mode)) 
    return Dist

Примените полученную функцию. Сделайте список списков расстояний

In [11]:
listOfDistNorm1 = []
listOfDistNorm2 = []

for i in range(len(X)):
  listOfDistNorm1.append(dist(X[i], Y[i], 1))
  listOfDistNorm2.append(dist(X[i], Y[i], 2))

print(listOfDistNorm1)

[[0.0, 1.1676715992006819, 0.7586543044725793, 1.3272598752246898, 1.095177859831463, 1.1676715992006819, 0.0, 0.40901729472810255, 0.45820649386622925, 0.6604854680390978, 0.7586543044725793, 0.40901729472810255, 0.0, 0.5686055707521104, 0.7115353605986808, 1.3272598752246898, 0.45820649386622925, 0.5686055707521104, 0.0, 0.2320820153932266, 1.095177859831463, 0.6604854680390978, 0.7115353605986808, 0.2320820153932266, 0.0], [0.0, 0.6817270174235146, 0.7681636563002168, 0.8504500169278796, 0.8580231113920029, 1.263438186028249, 0.16708476838744935, 0.4367433518551781, 0.4221204624836009, 0.29708951354209523, 0.6817270174235146, 0.0, 0.9823041085751054, 0.6634351076149138, 0.6427277652583918, 0.5817111686047345, 0.7336506039884488, 0.666042583506072, 0.26738960719728644, 0.9788165309656098, 0.7681636563002168, 0.9823041085751054, 0.0, 0.31886900096019166, 0.3395763433167136, 0.7232831738441872, 0.820087242865151, 0.33142030444503867, 0.714914501377819, 1.065253169842312, 0.850450016927

### Создание матриц 

Приведем несколько способов создания матриц в NumPy.

Самый простой способ — с помощью функции numpy.array(list, dtype=None, ...).

В качестве первого аргумента ей надо передать итерируемый объект, элементами которого являются другие итерируемые объекты одинаковой длины и содержащие данные одинакового типа.

Второй аргумент является опциональным и определяет тип данных матрицы. Его можно не задавать, тогда тип данных будет определен из типа элементов первого аргумента. При задании этого параметра будет произведена попытка приведения типов.

Например, матрицу из списка списков целых чисел можно создать следующим образом:

In [ ]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print ("Матрица:\n", a)

Матрица:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


Второй способ создания — с помощью встроенных функций numpy.eye(N, M=None, ...), numpy.zeros(shape, ...), numpy.ones(shape, ...).

Первая функция создает единичную матрицу размера  N×MN×M ; если  MM  не задан, то  M=NM=N .

Вторая и третья функции создают матрицы, состоящие целиком из нулей или единиц соответственно. В качестве первого аргумента необходимо задать размерность массива — кортеж целых чисел. В двумерном случае это набор из двух чисел: количество строк и столбцов матрицы.

#### Примеры:

In [ ]:
ones = np.eye(5)
print ("Единичная матрица:\n", ones)

Единичная матрица:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
onlyOnes = np.ones((7, 5))
print ("Матрица, состоящая из одних единиц:\n", onlyOnes)

Матрица, состоящая из одних единиц:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Обратите внимание: размерность массива задается не двумя аргументами функции, а одним — кортежем! Кортеж - набор чисел, заключенных в (). Поэтому помните о вторых () в аргументах!!!

И, наконец, третий способ — с помощью функции __`numpy.arange([start, ]stop, [step, ], ...)`__, которая создает одномерный массив последовательных чисел из промежутка __`[start, stop)`__ с заданным шагом __`step`__, и _метода_ __`array.reshape(shape)`__. 

Параметр __`shape`__, как и в предыдущем примере, задает размерность матрицы (кортеж чисел). Логика работы метода ясна из следующего примера:

In [ ]:
v = np.arange(0, 24, 2)
print ("Вектор-столбец:\n", v)

Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [ ]:
d = v.reshape((3, 4))
print ("Матрица:\n", d)

Матрица:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


#### Индексирование

In [ ]:
print ("Второй элемент третьей строки матрицы:", d[2, 1])

Второй элемент третьей строки матрицы: 18


Из матрицы можно получать целые строки или столбцы с помощью выражений __`array[i, :]`__ или __`array[:, j]`__ соответственно:

In [ ]:
print ("Вторая строка матрицы d:\n", d[1, :])
print ("Четвертый столбец матрицы d:\n", d[:, 3])

Вторая строка матрицы d:
 [ 8 10 12 14]
Четвертый столбец матрицы d:
 [ 6 14 22]


#### Транспонирование матриц

__Напоминание теории.__ __Транспонированной матрицей__ $A^{T}$ называется матрица, полученная из исходной матрицы $A$ заменой строк на столбцы. Формально: элементы матрицы $A^{T}$ определяются как $a^{T}_{ij} = a_{ji}$, где $a^{T}_{ij}$ — элемент матрицы $A^{T}$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

В `NumPy` транспонированная матрица вычисляется с помощью функции __`numpy.transpose()`__ или с помощью _метода_ __`array.T`__, где __`array`__ — нужный двумерный массив.

In [ ]:
a = np.array([[1, 2], [3, 4]])
aTransFun = np.transpose(a)
aTransT = a.T
print ('Матрица а: \n', a)
print ("Транспонирование функцией:\n", aTransFun)
print ("Транспонирование методом:\n",  aTransT)


Матрица а: 
 [[1 2]
 [3 4]]
Транспонирование функцией:
 [[1 3]
 [2 4]]
Транспонирование методом:
 [[1 3]
 [2 4]]


#### Диагональная матрица

Диагональная матрица содержит элементы главной диагонали исходной матрицы.
Для получения диагональной матрицы из исходной используется метод np.diag(), параметром которого является исходная матрица

In [ ]:
aDiag = np.diag(a)
print ('Диагональная матрица от а: \n', aDiag)

Диагональная матрица от а: 
 [1 4]


Если применить этот метод дважды к исходной матрице, то получим матрицу с 0 по всем элементам, кроме главной диагонали

In [ ]:
aDiagDouble = np.diag(np.diag(a))
print (aDiagDouble)

[[1 0]
 [0 4]]


## Задание 3

Преобразите полученные списки расстояний в квадратные матрицы 

In [12]:
listOfDistNorm1NP = np.array([np.array(listOfDistNorm1[0]), np.array(listOfDistNorm1[1]), np.array(listOfDistNorm1[2])]) #преобразуем список в массив
listOfMatrixDist1 = []
for k in range(listOfDistNorm1NP.size): # бежим по массиву
  n = int((listOfDistNorm1NP[k].size)**0.5) #получаем размерность матрицы
  listOfMatrixDist1.append(listOfDistNorm1NP[k].reshape(n,n))#добавляем значение в лист матриц и делаем матрицу н на н 
  print(listOfMatrixDist1[k])

listOfDistNorm2NP = np.array([np.array(listOfDistNorm2[0]), np.array(listOfDistNorm2[1]), np.array(listOfDistNorm2[2])])
listOfMatrixDist2 = []
for f in range(listOfDistNorm2NP.size):
  g = int((listOfDistNorm2NP[f].size)**0.5)
  listOfMatrixDist2.append(listOfDistNorm2NP[f].reshape(g,g))
  print(listOfMatrixDist2[f])

[[0.         1.1676716  0.7586543  1.32725988 1.09517786]
 [1.1676716  0.         0.40901729 0.45820649 0.66048547]
 [0.7586543  0.40901729 0.         0.56860557 0.71153536]
 [1.32725988 0.45820649 0.56860557 0.         0.23208202]
 [1.09517786 0.66048547 0.71153536 0.23208202 0.        ]]
[[0.         0.68172702 0.76816366 0.85045002 0.85802311 1.26343819
  0.16708477 0.43674335 0.42212046 0.29708951]
 [0.68172702 0.         0.98230411 0.66343511 0.64272777 0.58171117
  0.7336506  0.66604258 0.26738961 0.97881653]
 [0.76816366 0.98230411 0.         0.318869   0.33957634 0.72328317
  0.82008724 0.3314203  0.7149145  1.06525317]
 [0.85045002 0.66343511 0.318869   0.         0.02070734 0.41298817
  0.9023736  0.41370667 0.42832955 1.14753953]
 [0.85802311 0.64272777 0.33957634 0.02070734 0.         0.40541507
  0.9099467  0.42127976 0.43590265 1.15511262]
 [1.26343819 0.58171117 0.72328317 0.41298817 0.40541507 0.
  1.31536177 0.82669483 0.84131772 1.5605277 ]
 [0.16708477 0.7336506  0.8

## DataFrame

DataFrame являются удобным и общепринятым инструментом работы с датасетами. Для работы с ними нужна библиотека pandas. загрузим ее под кратким именем pd

In [14]:
import pandas as pd

### Создание DataFrame

DataFrame - это набор Series. Series - это вектор с заголовком. 

DataFrame можно создавать "вручную":

In [ ]:
df = pd.DataFrame({'col1':[1,2,3],'col2':[4,5,6]})
print (df)

или из массивов

In [ ]:
dfArr = pd.DataFrame(a, columns = ['col1','col2'])
print (dfArr)

   col1  col2
0     1     2
1     3     4


Подробная информация по созданию DataFrame есть в документации pandas http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html

#### Сохранение DataFrame в файл

DataFrame содержит ряд методов по сохранению в файл. Все они начинаются с to_
Сохраним полученный dataframe в excel

In [ ]:
dfArr.to_excel('test.xlsx')

Файл запишется в папку проекта

## Задание 4

Создайте на основе полученного массива DataFrame и запишите его в файл excel

In [15]:
nameColums = ["column " + str(i) for i in range(listOfMatrixDist1[1].shape[0])] #делаем названия колонок 
dfArr = pd.DataFrame(listOfMatrixDist1[1], columns = nameColums) # создаем таблицу из листа матриц
print (dfArr)
dfArr.to_excel("DataFrame.xlsx")

   column 0  column 1  column 2  ...  column 7  column 8  column 9
0  0.000000  0.681727  0.768164  ...  0.436743  0.422120  0.297090
1  0.681727  0.000000  0.982304  ...  0.666043  0.267390  0.978817
2  0.768164  0.982304  0.000000  ...  0.331420  0.714915  1.065253
3  0.850450  0.663435  0.318869  ...  0.413707  0.428330  1.147540
4  0.858023  0.642728  0.339576  ...  0.421280  0.435903  1.155113
5  1.263438  0.581711  0.723283  ...  0.826695  0.841318  1.560528
6  0.167085  0.733651  0.820087  ...  0.488667  0.474044  0.245166
7  0.436743  0.666043  0.331420  ...  0.000000  0.398653  0.733833
8  0.422120  0.267390  0.714915  ...  0.398653  0.000000  0.719210
9  0.297090  0.978817  1.065253  ...  0.733833  0.719210  0.000000

[10 rows x 10 columns]


## Задание 5

Отсортируйте по возрастанию расстояния в DataFrame для любой из точек. Используйте метод DataFrame.sort_values()

In [16]:
dfDistSort = dfArr.sort_values("column 0") # сортируем по возрастанию нулевой столбец
dfDistSort

column 0  column 1  column 2  ...  column 7  column 8  column 9
0  0.000000  0.681727  0.768164  ...  0.436743  0.422120  0.297090
6  0.167085  0.733651  0.820087  ...  0.488667  0.474044  0.245166
9  0.297090  0.978817  1.065253  ...  0.733833  0.719210  0.000000
8  0.422120  0.267390  0.714915  ...  0.398653  0.000000  0.719210
7  0.436743  0.666043  0.331420  ...  0.000000  0.398653  0.733833
1  0.681727  0.000000  0.982304  ...  0.666043  0.267390  0.978817
2  0.768164  0.982304  0.000000  ...  0.331420  0.714915  1.065253
3  0.850450  0.663435  0.318869  ...  0.413707  0.428330  1.147540
4  0.858023  0.642728  0.339576  ...  0.421280  0.435903  1.155113
5  1.263438  0.581711  0.723283  ...  0.826695  0.841318  1.560528

[10 rows x 10 columns]

## Запись в файл

Ниже приведена функцию записи списка значений в текстовый файл

In [17]:
def write_answer(listasn):
    with open("answer.txt", "w") as fout:
        fout.write("\n".join([str(num) for num in listasn]))

Поробуйте разобраться в ней самостоятельно и используйте ее для записи списка точек в порядке возрастания расстояния между ними

In [18]:
write_answer(dfDistSort.values.tolist())